// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventService.proto

public interface EventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp actionTimestamp = 1;</code>
   */
  boolean hasActionTimestamp();
  /**
   * <code>.google.protobuf.Timestamp actionTimestamp = 1;</code>
   */
  com.google.protobuf.Timestamp getActionTimestamp();
  /**
   * <code>.google.protobuf.Timestamp actionTimestamp = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getActionTimestampOrBuilder();

  /**
   * <code>string serviceName = 2;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>int64 userId = 3;</code>
   */
  long getUserId();

  /**
   * <code>.EventRequest.ActionType actionType = 4;</code>
   */
  int getActionTypeValue();
  /**
   * <code>.EventRequest.ActionType actionType = 4;</code>
   */
  EventRequest.ActionType getActionType();

  /**
   * <code>string resourceName = 5;</code>
   */
  java.lang.String getResourceName();
  /**
   * <code>string resourceName = 5;</code>
   */
  com.google.protobuf.ByteString
      getResourceNameBytes();

  /**
   * <code>.EventRequest.ResponseType responseType = 6;</code>
   */
  int getResponseTypeValue();
  /**
   * <code>.EventRequest.ResponseType responseType = 6;</code>
   */
  EventRequest.ResponseType getResponseType();
}
