package com.example.hotel.ena.systemevents;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventService.proto

import java.sql.*;

public  final class EventRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
        EventRequestOrBuilder {
  private EventRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EventRequest() {
    serviceName_ = "";
    userId_ = 0L;
    actionType_ = 0;
    resourceName_ = "";
    responseType_ = 0;
  }


  //MOGUCE DA NE TREBA
  public EventRequest(Object o, Timestamp from, String serviceName, long userId, String orElse, String resourceName, String orElse1) {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private EventRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (actionTimestamp_ != null) {
              subBuilder = actionTimestamp_.toBuilder();
            }
            actionTimestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(actionTimestamp_);
              actionTimestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            serviceName_ = s;
            break;
          }
          case 24: {

            userId_ = input.readInt64();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            actionType_ = rawValue;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            resourceName_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            responseType_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EventService.internal_static_EventRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EventService.internal_static_EventRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            EventRequest.class, EventRequest.Builder.class);
  }

  /*Protobuf enum {@code EventRequest.ActionType}*/
  public enum ActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /*<code>CREATE = 0;</code>*/
    CREATE(0),
    /* <code>DELETE = 1;</code>*/
    DELETE(1),
    /* <code>GET = 2;</code>*/
    GET(2),
    /*<code>UPDATE = 3;</code>*/
    UPDATE(3),
    /* <code>HEAD = 4;</code>*/
    HEAD(4),
    /* <code>PATCH = 5;</code>*/
    PATCH(5),
    /*<code>PUT = 6;</code>*/
    PUT(6),
    /* <code>TRACE = 7;</code>*/
    TRACE(7),
    /*<code>POST = 8;</code>*/
    POST(8),
    /* <code>OPTIONS = 9;</code>*/
    OPTIONS(9),
    UNRECOGNIZED(-1),
    ;

    /*<code>CREATE = 0;</code>*/
    public static final int CREATE_VALUE = 0;
    /* <code>DELETE = 1;</code>*/
    public static final int DELETE_VALUE = 1;
    /* <code>GET = 2;</code> */
    public static final int GET_VALUE = 2;
    /* <code>UPDATE = 3;</code> */
    public static final int UPDATE_VALUE = 3;
    /*<code>HEAD = 4;</code>*/
    public static final int HEAD_VALUE = 4;
    /*<code>PATCH = 5;</code>*/
    public static final int PATCH_VALUE = 5;
    /*<code>PUT = 6;</code>*/
    public static final int PUT_VALUE = 6;
    /*<code>TRACE = 7;</code>*/
    public static final int TRACE_VALUE = 7;
    /*<code>POST = 8;</code>*/
    public static final int POST_VALUE = 8;
    /*<code>OPTIONS = 9;</code>*/
    public static final int OPTIONS_VALUE = 9;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /* @deprecated Use {@link #forNumber(int)} instead.*/
    @Deprecated
    public static ActionType valueOf(int value) {
      return forNumber(value);
    }

    public static ActionType forNumber(int value) {
      switch (value) {
        case 0: return CREATE;
        case 1: return DELETE;
        case 2: return GET;
        case 3: return UPDATE;
        case 4: return HEAD;
        case 5: return PATCH;
        case 6: return PUT;
        case 7: return TRACE;
        case 8: return POST;
        case 9: return OPTIONS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
            public ActionType findValueByNumber(int number) {
              return ActionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return EventRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final ActionType[] VALUES = values();

    public static ActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ActionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EventRequest.ActionType)
  }

  /*Protobuf enum {@code EventRequest.ResponseType}*/
  public enum ResponseType
      implements com.google.protobuf.ProtocolMessageEnum {
    /*<code>Success = 0;</code>*/
    Success(0),
    /*<code>Failure = 1;</code>*/
    Failure(1),
    UNRECOGNIZED(-1),
    ;

    /*<code>Success = 0;</code>*/
    public static final int Success_VALUE = 0;
    /*<code>Failure = 1;</code>*/
    public static final int Failure_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /*@deprecated Use {@link #forNumber(int)} instead.*/
    @Deprecated
    public static ResponseType valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseType forNumber(int value) {
      switch (value) {
        case 0: return Success;
        case 1: return Failure;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
            public ResponseType findValueByNumber(int number) {
              return ResponseType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return EventRequest.getDescriptor().getEnumTypes().get(1);
    }

    private static final ResponseType[] VALUES = values();

    public static ResponseType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResponseType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EventRequest.ResponseType)
  }

  public static final int ACTIONTIMESTAMP_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp actionTimestamp_;
  /*<code>.google.protobuf.Timestamp actionTimestamp = 1;</code>*/
  public boolean hasActionTimestamp() {
    return actionTimestamp_ != null;
  }
  /*code>.google.protobuf.Timestamp actionTimestamp = 1;</code>*/
  public com.google.protobuf.Timestamp getActionTimestamp() {
    return actionTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : actionTimestamp_;
  }
  /*<code>.google.protobuf.Timestamp actionTimestamp = 1;</code>*/
  public com.google.protobuf.TimestampOrBuilder getActionTimestampOrBuilder() {
    return getActionTimestamp();
  }

  public static final int SERVICENAME_FIELD_NUMBER = 2;
  private volatile Object serviceName_;
  /*<code>string serviceName = 2;</code>*/
  public String getServiceName() {
    Object ref = serviceName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }
  /*<code>string serviceName = 2;</code>*/
  public com.google.protobuf.ByteString
      getServiceNameBytes() {
    Object ref = serviceName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERID_FIELD_NUMBER = 3;
  private long userId_;
  /* <code>int64 userId = 3;</code>*/
  public long getUserId() {
    return userId_;
  }

  public static final int ACTIONTYPE_FIELD_NUMBER = 4;
  private int actionType_;
  /*<code>.EventRequest.ActionType actionType = 4;</code>*/

  public int getActionTypeValue() {
    return actionType_;
  }
  /*
    <code>.EventRequest.ActionType actionType = 4;</code>
   */
  public EventRequest.ActionType getActionType() {
    EventRequest.ActionType result = EventRequest.ActionType.valueOf(actionType_);
    return result == null ? EventRequest.ActionType.UNRECOGNIZED : result;
  }

  public static final int RESOURCENAME_FIELD_NUMBER = 5;
  private volatile Object resourceName_;
  /**
   * <code>string resourceName = 5;</code>
   */
  public String getResourceName() {
    Object ref = resourceName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      resourceName_ = s;
      return s;
    }
  }
  /**
   * <code>string resourceName = 5;</code>
   */
  public com.google.protobuf.ByteString
      getResourceNameBytes() {
    Object ref = resourceName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      resourceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSETYPE_FIELD_NUMBER = 6;
  private int responseType_;
  /**
   * <code>.EventRequest.ResponseType responseType = 6;</code>
   */
  public int getResponseTypeValue() {
    return responseType_;
  }
  /**
   * <code>.EventRequest.ResponseType responseType = 6;</code>
   */
  public EventRequest.ResponseType getResponseType() {
    EventRequest.ResponseType result = EventRequest.ResponseType.valueOf(responseType_);
    return result == null ? EventRequest.ResponseType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (actionTimestamp_ != null) {
      output.writeMessage(1, getActionTimestamp());
    }
    if (!getServiceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceName_);
    }
    if (userId_ != 0L) {
      output.writeInt64(3, userId_);
    }
    if (actionType_ != EventRequest.ActionType.CREATE.getNumber()) {
      output.writeEnum(4, actionType_);
    }
    if (!getResourceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, resourceName_);
    }
    if (responseType_ != EventRequest.ResponseType.Success.getNumber()) {
      output.writeEnum(6, responseType_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (actionTimestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getActionTimestamp());
    }
    if (!getServiceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serviceName_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, userId_);
    }
    if (actionType_ != EventRequest.ActionType.CREATE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, actionType_);
    }
    if (!getResourceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, resourceName_);
    }
    if (responseType_ != EventRequest.ResponseType.Success.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, responseType_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof EventRequest)) {
      return super.equals(obj);
    }
    EventRequest other = (EventRequest) obj;

    boolean result = true;
    result = result && (hasActionTimestamp() == other.hasActionTimestamp());
    if (hasActionTimestamp()) {
      result = result && getActionTimestamp()
          .equals(other.getActionTimestamp());
    }
    result = result && getServiceName()
        .equals(other.getServiceName());
    result = result && (getUserId()
        == other.getUserId());
    result = result && actionType_ == other.actionType_;
    result = result && getResourceName()
        .equals(other.getResourceName());
    result = result && responseType_ == other.responseType_;
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasActionTimestamp()) {
      hash = (37 * hash) + ACTIONTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getActionTimestamp().hashCode();
    }
    hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + ACTIONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + actionType_;
    hash = (37 * hash) + RESOURCENAME_FIELD_NUMBER;
    hash = (53 * hash) + getResourceName().hashCode();
    hash = (37 * hash) + RESPONSETYPE_FIELD_NUMBER;
    hash = (53 * hash) + responseType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static EventRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EventRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EventRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EventRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EventRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EventRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EventRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EventRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static EventRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static EventRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static EventRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EventRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(EventRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EventRequest)
      EventRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EventService.internal_static_EventRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EventService.internal_static_EventRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EventRequest.class, EventRequest.Builder.class);
    }

    // Construct using EventRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (actionTimestampBuilder_ == null) {
        actionTimestamp_ = null;
      } else {
        actionTimestamp_ = null;
        actionTimestampBuilder_ = null;
      }
      serviceName_ = "";

      userId_ = 0L;

      actionType_ = 0;

      resourceName_ = "";

      responseType_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EventService.internal_static_EventRequest_descriptor;
    }

    public EventRequest getDefaultInstanceForType() {
      return EventRequest.getDefaultInstance();
    }

    public EventRequest build() {
      EventRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public EventRequest buildPartial() {
      EventRequest result = new EventRequest(this);
      if (actionTimestampBuilder_ == null) {
        result.actionTimestamp_ = actionTimestamp_;
      } else {
        result.actionTimestamp_ = actionTimestampBuilder_.build();
      }
      result.serviceName_ = serviceName_;
      result.userId_ = userId_;
      result.actionType_ = actionType_;
      result.resourceName_ = resourceName_;
      result.responseType_ = responseType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof EventRequest) {
        return mergeFrom((EventRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(EventRequest other) {
      if (other == EventRequest.getDefaultInstance()) return this;
      if (other.hasActionTimestamp()) {
        mergeActionTimestamp(other.getActionTimestamp());
      }
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        onChanged();
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.actionType_ != 0) {
        setActionTypeValue(other.getActionTypeValue());
      }
      if (!other.getResourceName().isEmpty()) {
        resourceName_ = other.resourceName_;
        onChanged();
      }
      if (other.responseType_ != 0) {
        setResponseTypeValue(other.getResponseTypeValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      EventRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (EventRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Timestamp actionTimestamp_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> actionTimestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp actionTimestamp = 1;</code>
     */
    public boolean hasActionTimestamp() {
      return actionTimestampBuilder_ != null || actionTimestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp actionTimestamp = 1;</code>
     */
    public com.google.protobuf.Timestamp getActionTimestamp() {
      if (actionTimestampBuilder_ == null) {
        return actionTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : actionTimestamp_;
      } else {
        return actionTimestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp actionTimestamp = 1;</code>
     */
    public Builder setActionTimestamp(com.google.protobuf.Timestamp value) {
      if (actionTimestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionTimestamp_ = value;
        onChanged();
      } else {
        actionTimestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp actionTimestamp = 1;</code>
     */
    public Builder setActionTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (actionTimestampBuilder_ == null) {
        actionTimestamp_ = builderForValue.build();
        onChanged();
      } else {
        actionTimestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp actionTimestamp = 1;</code>
     */
    public Builder mergeActionTimestamp(com.google.protobuf.Timestamp value) {
      if (actionTimestampBuilder_ == null) {
        if (actionTimestamp_ != null) {
          actionTimestamp_ =
            com.google.protobuf.Timestamp.newBuilder(actionTimestamp_).mergeFrom(value).buildPartial();
        } else {
          actionTimestamp_ = value;
        }
        onChanged();
      } else {
        actionTimestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /*
     * <code>.google.protobuf.Timestamp actionTimestamp = 1;</code>
     */
    public Builder clearActionTimestamp() {
      if (actionTimestampBuilder_ == null) {
        actionTimestamp_ = null;
        onChanged();
      } else {
        actionTimestamp_ = null;
        actionTimestampBuilder_ = null;
      }

      return this;
    }
    /*
     * <code>.google.protobuf.Timestamp actionTimestamp = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getActionTimestampBuilder() {

      onChanged();
      return getActionTimestampFieldBuilder().getBuilder();
    }
    /*
     * <code>.google.protobuf.Timestamp actionTimestamp = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getActionTimestampOrBuilder() {
      if (actionTimestampBuilder_ != null) {
        return actionTimestampBuilder_.getMessageOrBuilder();
      } else {
        return actionTimestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : actionTimestamp_;
      }
    }
    /*
     * <code>.google.protobuf.Timestamp actionTimestamp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
        getActionTimestampFieldBuilder() {
      if (actionTimestampBuilder_ == null) {
        actionTimestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getActionTimestamp(),
                getParentForChildren(),
                isClean());
        actionTimestamp_ = null;
      }
      return actionTimestampBuilder_;
    }

    private Object serviceName_ = "";
    /*
     * <code>string serviceName = 2;</code>
     */
    public String getServiceName() {
      Object ref = serviceName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /*
     * <code>string serviceName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /*
     * <code>string serviceName = 2;</code>
     */
    public Builder setServiceName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      serviceName_ = value;
      onChanged();
      return this;
    }
    /*
     * <code>string serviceName = 2;</code>
     */
    public Builder clearServiceName() {

      serviceName_ = getDefaultInstance().getServiceName();
      onChanged();
      return this;
    }
    /*
     * <code>string serviceName = 2;</code>
     */
    public Builder setServiceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      serviceName_ = value;
      onChanged();
      return this;
    }

    private long userId_ ;
    /*
     * <code>int64 userId = 3;</code>
     */
    public long getUserId() {
      return userId_;
    }
    /*
     * <code>int64 userId = 3;</code>
     */
    public Builder setUserId(long value) {

      userId_ = value;
      onChanged();
      return this;
    }
    /*
     * <code>int64 userId = 3;</code>
     */
    public Builder clearUserId() {

      userId_ = 0L;
      onChanged();
      return this;
    }

    private int actionType_ = 0;
    /*
     * <code>.EventRequest.ActionType actionType = 4;</code>
     */
    public int getActionTypeValue() {
      return actionType_;
    }
    /*
     * <code>.EventRequest.ActionType actionType = 4;</code>
     */
    public Builder setActionTypeValue(int value) {
      actionType_ = value;
      onChanged();
      return this;
    }
    /*
     * <code>.EventRequest.ActionType actionType = 4;</code>
     */
    public EventRequest.ActionType getActionType() {
      EventRequest.ActionType result = EventRequest.ActionType.valueOf(actionType_);
      return result == null ? EventRequest.ActionType.UNRECOGNIZED : result;
    }
    /*
     * <code>.EventRequest.ActionType actionType = 4;</code>
     */
    public Builder setActionType(EventRequest.ActionType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      actionType_ = value.getNumber();
      onChanged();
      return this;
    }
    /*
     * <code>.EventRequest.ActionType actionType = 4;</code>
     */
    public Builder clearActionType() {

      actionType_ = 0;
      onChanged();
      return this;
    }

    private Object resourceName_ = "";
    /*
     * <code>string resourceName = 5;</code>
     */
    public String getResourceName() {
      Object ref = resourceName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        resourceName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /*
     * <code>string resourceName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getResourceNameBytes() {
      Object ref = resourceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        resourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /*
     * <code>string resourceName = 5;</code>
     */
    public Builder setResourceName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      resourceName_ = value;
      onChanged();
      return this;
    }
    /*
     * <code>string resourceName = 5;</code>
     */
    public Builder clearResourceName() {

      resourceName_ = getDefaultInstance().getResourceName();
      onChanged();
      return this;
    }
    /*
     * <code>string resourceName = 5;</code>
     */
    public Builder setResourceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      resourceName_ = value;
      onChanged();
      return this;
    }

    private int responseType_ = 0;
    /*
     * <code>.EventRequest.ResponseType responseType = 6;</code>
     */
    public int getResponseTypeValue() {
      return responseType_;
    }
    /*
     * <code>.EventRequest.ResponseType responseType = 6;</code>
     */
    public Builder setResponseTypeValue(int value) {
      responseType_ = value;
      onChanged();
      return this;
    }
    /*
     * <code>.EventRequest.ResponseType responseType = 6;</code>
     */
    public EventRequest.ResponseType getResponseType() {
      EventRequest.ResponseType result = EventRequest.ResponseType.valueOf(responseType_);
      return result == null ? EventRequest.ResponseType.UNRECOGNIZED : result;
    }
    /*
     * <code>.EventRequest.ResponseType responseType = 6;</code>
     */
    public Builder setResponseType(EventRequest.ResponseType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      responseType_ = value.getNumber();
      onChanged();
      return this;
    }
    /*
     * <code>.EventRequest.ResponseType responseType = 6;</code>
     */
    public Builder clearResponseType() {

      responseType_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:EventRequest)
  }

  // @@protoc_insertion_point(class_scope:EventRequest)
  private static final EventRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EventRequest();
  }

  public static EventRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventRequest>
      PARSER = new com.google.protobuf.AbstractParser<EventRequest>() {
    public EventRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EventRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<EventRequest> getParserForType() {
    return PARSER;
  }

  public EventRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

