package com.example.hotel.ena.systemevents;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventService.proto

public interface EventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eventResponseText = 1;</code>
   */
  java.lang.String getEventResponseText();
  /**
   * <code>string eventResponseText = 1;</code>
   */
  com.google.protobuf.ByteString
      getEventResponseTextBytes();
}
