package com.example.hotel.ena.systemevents;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventService.proto

public final class EventService {
  private EventService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EventResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022EventService.proto\032\037google/protobuf/ti" +
      "mestamp.proto\"\203\003\n\014EventRequest\0223\n\017action" +
      "Timestamp\030\001 \001(\0132\032.google.protobuf.Timest" +
      "amp\022\023\n\013serviceName\030\002 \001(\t\022\016\n\006userId\030\003 \001(\003" +
      "\022,\n\nactionType\030\004 \001(\0162\030.EventRequest.Acti" +
      "onType\022\024\n\014resourceName\030\005 \001(\t\0220\n\014response" +
      "Type\030\006 \001(\0162\032.EventRequest.ResponseType\"y" +
      "\n\nActionType\022\n\n\006CREATE\020\000\022\n\n\006DELETE\020\001\022\007\n\003" +
      "GET\020\002\022\n\n\006UPDATE\020\003\022\010\n\004HEAD\020\004\022\t\n\005PATCH\020\005\022\007" +
      "\n\003PUT\020\006\022\t\n\005TRACE\020\007\022\010\n\004POST\020\010\022\013\n\007OPTIONS\020",
      "\t\"(\n\014ResponseType\022\013\n\007Success\020\000\022\013\n\007Failur" +
      "e\020\001\"*\n\rEventResponse\022\031\n\021eventResponseTex" +
      "t\030\001 \001(\t27\n\rEventsService\022&\n\005hello\022\r.Even" +
      "tRequest\032\016.EventResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_EventRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EventRequest_descriptor,
        new java.lang.String[] { "ActionTimestamp", "ServiceName", "UserId", "ActionType", "ResourceName", "ResponseType", });
    internal_static_EventResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EventResponse_descriptor,
        new java.lang.String[] { "EventResponseText", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
